simgrid/simgrid

- src/smpi/smpi_pmpi.c
- src/smpi/smpi_replay.c
When the tracing/smpi/internals option is not enabled, some PTP messages
are showed for send and receive operations, both on tracing and
replaying. When the option is enabled, additional messages are
generated, so duplicate messages for send and receive operations
appear on the log.
Initially I thought that the idea was to only show PTP messages when the
tracing/smpi/internals option is enabled. After talking to Arnaud it
seems that is not the case. So I changed the code so both funcionalities
are present: PTP messages for send and receive operations when the
option is disabled and all PTP messages when the option is enabled, as
expected.
I have little knowledge about the internals of the Simgrid code, this fix was
what worked for me in my experiments. It is possible that this is not the …
> Fix duplicate PTP messages when tracing/smpi/internals is enabled

- src/simix/libsmx.cpp
- src/surf/host_ptask_L07.cpp
If there is no communications in your parallel task, it is useless to allocate a host_nb*host_nb full of 0.
> Allows the bytes_amount argument of MSG_parallel_task_create to be null

- src/include/surf/maxmin.h
- src/surf/maxmin.cpp
- src/surf/maxmin_private.hpp
- src/surf/network_cm02.cpp
Modification to the SURF LMM:
-> Enabling concurrency control and monitoring 
-> Improving efficiency of lmm_update_modified_set
-> Removing  dead code and adding comments
> Adding concurrency to SURF LMM, with oldstyle element set

- include/simgrid/msg.h
- src/msg/msg_synchro.cpp
There were no way of getting the value of the semaphore with MSG_sem_get_capacity.
> Add a return value for MSG_sem_get_capacity

- src/surf/plugins/energy.cpp
Hello,
When I updated SimGrid and tried to use my simulator with old energy platform files
(watts are defined as "min:max" instead of "idle:min:max"), I had some obscure OOB error.
I updated the assertion about the number of ":" subparts and
realized one string was not freed, so I fixed it too.
Best regards,
Millian
> [Energy platform parsing] assert + memory leak

- include/smpi/smpi.h
- src/smpi/smpi_bench.cpp
This function simply calls `smpi_execute`, but take care of stopping and restarting the bench.
It is useful to replace expensive pieces of application code that cannot be wrapped by a `SMPI_SAMPLE` because of their irregularity. For instance, in HPL, we use it to simulate `dgemm` and `dtrsm`.
Before that, we used `smpi_usleep`, but this one has two drawbacks:
- It takes a virtual time and not a real time, so you have to redo your linear regression each time you change the speed of the platform you simulate.
- It is a sleep, so it works for time estimation but not for energy.
Regarding the name of the function, I am not sure it is very explicit, but I had no better idea.
> Add smpi_execute_public

- doc/doxygen/options.doc
- src/simgrid/sg_config.cpp
- src/smpi/smpi_shared.cpp
This adds an option to `smpirun` asking to use huge pages for the calls to `SMPI_SHARED_MALLOC` and `SMPI_PARTIAL_SHARED_MALLOC`.
To use it:
```bash
mkdir /home/huge && sudo mount none /home/huge -t hugetlbfs -o rw,mode=0777
sudo sh -c "/bin/echo 1 > /proc/sys/vm/nr_hugepages"
smpirun --cfg=smpi/shared-malloc-hugepage:/home/huge --cfg=smpi/shared-malloc-blocksize:2097152 [...]
```
For very large allocations, the page table grows very large and the kernel takes a lot of time working on this table, stalling the simulation.
For instance, without huge pages, HPL with a matrix of size 6e5 has a page table of 5.5GB and the simulation drops below 40% of CPU utilization.
Using huge pages fix this. Of course this only shifts the problem further, but this is an easy fix.
Currently, the size of a …
> Add support for huge pages in SMPI

- src/surf/plugins/host_energy.cpp
fixed energy plugin: getCurrentWattsValue was not returning watts_of when the host is off
> Fixed energy plugin: returning watts_off when host is off

- FindSimGrid.cmake
Enhancements:
- Use FindPackageHandleStandardArgs to properly accept find_package arguments
- Extract the version from  `SIMGRID_(MAJOR, MINOR, PATCH)`
- Define a target `SimGrid::SimGrid` in addition to the variables (modern CMake, variables should be deprecated...)
- Handle C++11 requirement as much as possible (note: If you stop using -std=gnu++11 you might need to set the property `CXX_EXTENSIONS OFF`: https://cliutils.gitlab.io/modern-cmake/chapters/cpp11.html)
> Modernize FindSimGrid

- src/smpi/internals/smpi_replay.cpp
Hello.
This PR allows a more dynamic replay of SMPI traces by changing the type of the `storage` variable.
It also proposes to simply use PIDs instead of PIDs-1 in all indexes, as an `unordered_map` does not need to be 0-based (was a vector before the PR).
I'll do a separate PR for the examples going with this code.
> Dynamic and manual replay of SMPI traces

- src/simix/smx_global.cpp
It was using relative time deltas instead of absolute time.
> Fix breakpoint option

- include/simgrid/s4u/Mailbox.hpp
- src/s4u/s4u_Mailbox.cpp
I have the following scenario which I have not been able to simulate with the current SimGrid mailbox synchronization primitives
I have actors which operate in an infinite loop where they check if they have some message ready from one of theirs peers and if that's not the case they sleep for a fixed short amount of time before checking again.
In a sort of pseudo-code it looks like this:
**Initialization**
Every actor has a mailbox where they specify themselves as the receiver because that way according to `Mailbox.hpp`:
> It means that the communications sent to this mailbox will start flowing to
>   * its host even before he does a recv(). This models the real behavior of TCP
>   * and MPI communications, amongst other."
initialization code:
``` …
```
> Add method to check if a mailbox has a message ready to be consumed without having to wait

- tools/cmake/Distrib.cmake
- tools/pkg-config/simgrid.pc.in
[pkg-config] eases the utilization of software components by letting the developers define how the components they work on should be used.
This commit generates and installs a very simple `simgrid.pc` for [pkg-config].
This allows users to include/link SimGrid without knowing internal details.
``` Make
my-simulator: my-simulator.cpp
g++ my-simulator.cpp ‘pkg-config --cflags --libs simgrid‘
```
``` Meson
project('my-simulator', 'cpp')
simgrid = dependency('simgrid')
executable('my-simulator', 'my-simulator.cpp', dependencies : simgrid)
```
[Meson]: https://mesonbuild.com/
[pkg-config]: https://www.freedesktop.org/wiki/Software/pkg-config/
> Provide a pkg-config file for SimGrid

- CMakeLists.txt
- docs/source/Configuring_SimGrid.rst
Currently, when using cmake as:
```
cmake -DCMAKE_BUILD_TYPE=Debug
```
the g++ flags get set as something like "`-g -O2`".  This makes it difficult to use GDB.  This commit will add the `-O0` flag after the `-O2` in the `Debug` case, to ensure easier debugging.
Feel free to modify my comment in the commit, if you like.
> Add '-O0' flag for: cmake -DCMAKE_BUILD_TYPE=Debug

- docs/source/Tutorial_Algorithms.rst
In the "[Simulating Algorithms](https://simgrid.org/doc/latest/Tutorial_Algorithms.html)" section of the docs, a master / worker application is used as an example. I think that when presenting actors a "worker" has been written in place of "master"
> Fix a doc error about actors (Tutorial_algorithms)

- src/smpi/internals/smpi_shared.cpp
The two macros `ALIGN_UP` and `ALIGN_DOWN` used by the shared malloc hugepages gave the wrong result in a logical operation because of a different precision type.
The following minimal example ilustrates this:
```C++
#include <stdio.h>
#include <cstdint>
#define ALIGN_UP(n, align) (((n) + (align)-1) & -(align))
constexpr unsigned HUGE_PAGE_SIZE = 1U << 21;
int main(){
void* mem;
void* allocated_ptr = (void*)0x7ffdffef1000;
mem = (void*)ALIGN_UP((int64_t)allocated_ptr, HUGE_PAGE_SIZE);
printf("ap: %p\n", allocated_ptr);
printf("mem: %p\n", mem);
}
```
The value `0x7ffdffef1000` is returned from `mmap` in simgrid code, but when `ALIGH_UP` is applied, `mem` is `NULL`.
The `align` parameter should be of the same type of `n` before the `-(align)`.
Some of the calls were already casting the …
> cast hugepages macros parameters to int64

- .github/workflows/docker.yml
- tools/docker/Makefile
Build is setup once a week (sundays) for all images in tools/docker, using the makefile, or on demand.
Fixes the makefile for stable (and adds tuto-mc to the all target)
Please squash before merging.
***Before merging*** : needs secrets DOCKERHUB_USERNAME and DOCKERHUB_TOKEN to have been generated and stored in the repo options ( check https://docs.docker.com/docker-hub/access-tokens/ and https://github.com/Azure/actions-workflow-samples/blob/master/assets/create-secrets-for-GitHub-workflows.md )
pushing was not tested, obviously.. so it may fail at start
> Add docker images to ci

- src/smpi/smpicc.in
- src/smpi/smpicxx.in
This changes the order of the CMDLINE to place the CFLAGS after CMDARGS.
Useful when CMDARGS has an fPIE (coming from a CMake POSITION_INDEPENDENT_CODE, for example), this will ensure a fPIC that may be present in CFLAGS to be after the fPIE in CMDARGS.
> Ensure a final fPIC in case CMDARGS has a fPIE

- examples/cpp/CMakeLists.txt
- examples/cpp/exec-suspend/s4u-exec-suspend.cpp
- examples/cpp/exec-suspend/s4u-exec-suspend.tesh
- src/s4u/s4u_Activity.cpp
If an activity was suspended and resumed in code several times, after the second suspend() the activity wasn't actually suspended(), and the remaining flops continued decreasing over the simulation.
> Fix bug when suspend() after resume() didn't work

- include/simgrid/s4u/Task.hpp
- src/s4u/s4u_Task.cpp
The main idea behind these changes, is to give the user better options while handling instances throughout a simulation. 
The Task class was modified to:
1. Allow the user to check the number of instances with `get_instance_count()`.
2. Use a new callback `on_instance_completion_cb()` that is executed when a instance ends. (excluding the dispatcher and the collector).
> Mods to s4u_tasks to allow better tracking of instances throughout
